
package ctwo;

import java.sql.Connection;
import java.util.ArrayList;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel; 

public class CleaningServiceInfo extends javax.swing.JFrame {

    
    public CleaningServiceInfo() {
        initComponents();
        setLocationRelativeTo(null);
        show_user();
    }
public Connection connection;  
    public ArrayList<UserT>userList()
    {
      ArrayList<UserT>userList = new ArrayList<>();

         try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=CMS", "sa", "62625522");
         
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement
                    .executeQuery("select Os.ServiceId,Os.ServiceName,P.ServiceFee,P.CurrentStatus,S.ServiceAvailableDay from OurService Os inner join Project P on Os.ServiceId=P.ServiceId inner join ServiceAvailability S on P.ServiceId=S.ServiceId where Os.ServiceId  not in (10,12)");
            
        
             UserT user;
            
            while(resultSet.next())
         {
            user = new UserT(resultSet.getInt("ServiceId"),resultSet.getString("ServiceName"),resultSet.getString("ServiceFee"),resultSet.getString("CurrentStatus"),resultSet.getString("ServiceAvailableDay"));
            userList.add(user);
            

         }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
         return userList;
    
    
    
    }
      
 public void show_user()
 {
   ArrayList<UserT>list = userList();
   DefaultTableModel model =(DefaultTableModel) CleaningServiceInfoTable.getModel();
   Object[] row = new Object[5];


   for(int i = 0;i<list.size();i++)
   {
     
     row[0]=list.get(i).getServiceId();
     row[1]=list.get(i).getServiceName();
     row[2]=list.get(i).getServiceFee();
     row[3]=list.get(i).getCurrentStatus();
     row[4]=list.get(i).getServiceAvailableDay();
    
    
     model.addRow(row);
   
   }
 
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CleaningServiceInfoTable = new javax.swing.JTable();
        BackToService = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ServiceId = new javax.swing.JTextField();
        ServiceName = new javax.swing.JTextField();
        ServiceFee = new javax.swing.JTextField();
        CurrentStatus = new javax.swing.JTextField();
        ServiceAvailableDay = new javax.swing.JTextField();
        SearchServiceName = new javax.swing.JTextField();
        Clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 250, 250));
        jLabel1.setText("Cleaning & ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 130, 80));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(250, 250, 250));
        jLabel2.setText("Maid Service");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 140, 80));

        jLabel3.setBackground(new java.awt.Color(255, 204, 0));
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 150, 570));

        CleaningServiceInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ServiceId", "ServiceName", "ServiceFee", "CurrentStatus", "ServiceAvailableDay"
            }
        ));
        CleaningServiceInfoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CleaningServiceInfoTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CleaningServiceInfoTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 0, 1180, 200));

        BackToService.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        BackToService.setText("BackToService");
        BackToService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToServiceActionPerformed(evt);
            }
        });
        jPanel1.add(BackToService, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 140, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Search(Enter ServiceName) ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 200, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("ServiceId");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 90, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("ServiceName");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 90, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("ServiceFee");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 90, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("CurrentStatus");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 100, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("ServiceAvailableDay");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 140, 40));
        jPanel1.add(ServiceId, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 220, 30));
        jPanel1.add(ServiceName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 220, 30));

        ServiceFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServiceFeeActionPerformed(evt);
            }
        });
        jPanel1.add(ServiceFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 320, 220, 30));

        CurrentStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrentStatusActionPerformed(evt);
            }
        });
        jPanel1.add(CurrentStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 220, 30));
        jPanel1.add(ServiceAvailableDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 250, 30));

        SearchServiceName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchServiceNameKeyReleased(evt);
            }
        });
        jPanel1.add(SearchServiceName, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 250, 230, 30));

        Clear.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Clear.setText("CLEAR");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        jPanel1.add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 330, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1336, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ServiceFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServiceFeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ServiceFeeActionPerformed

    private void CurrentStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrentStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CurrentStatusActionPerformed

    private void CleaningServiceInfoTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CleaningServiceInfoTableMouseClicked
       int i = CleaningServiceInfoTable.getSelectedRow();
        TableModel model = CleaningServiceInfoTable.getModel();
        
        ServiceId.setText(model.getValueAt(i,1).toString());
        ServiceName.setText(model.getValueAt(i,1).toString());
        ServiceFee.setText(model.getValueAt(i,2).toString());
        CurrentStatus.setText(model.getValueAt(i,4).toString());
        ServiceAvailableDay.setText(model.getValueAt(i,5).toString());
        
    }//GEN-LAST:event_CleaningServiceInfoTableMouseClicked

    private void SearchServiceNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchServiceNameKeyReleased
         try {
           
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=checkpointnotwo;selectMethod=cursor", "sa", "123456");
            
            String sql ="select Os.ServiceId,Os.ServiceName,P.ServiceFee,P.CurrentStatus,S.ServiceAvailableDay from OurService Os inner join Project P on Os.ServiceId=P.ServiceId inner join ServiceAvailability S on P.ServiceId=S.ServiceId and Os.ServiceId  not in (10,12) where ServiceName like ?";
            PreparedStatement pst = connection.prepareStatement(sql);
            pst.setString(1, SearchServiceName.getText()+"%");
            ResultSet rs =pst.executeQuery();
            if(rs.next())
            {
              String setServiceId = rs.getString("ServiceId");
             ServiceId.setText(setServiceId);
              String setServiceName = rs.getString("ServiceName");
              ServiceName.setText(setServiceName);
             String setServiceFee= rs.getString("ServiceFee");
             ServiceFee.setText(setServiceFee);
             String setCurrentStatus= rs.getString("CurrentStatus");
             CurrentStatus.setText(setCurrentStatus);
             String setServiceAvailableDay= rs.getString("ServiceAvailableDay");
             ServiceAvailableDay.setText(setServiceAvailableDay);
             
              
            
            }
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(null, e);
         
         }
    }//GEN-LAST:event_SearchServiceNameKeyReleased

    private void BackToServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToServiceActionPerformed
        Service as=new Service();
         as.setVisible(true);
         new CleaningServiceInfo ().setVisible(false);
         dispose();
    }//GEN-LAST:event_BackToServiceActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        ServiceId.setText("");
         ServiceName.setText("");
         ServiceFee.setText("");
         CurrentStatus.setText("");
         ServiceAvailableDay.setText("");
        
    }//GEN-LAST:event_ClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CleaningServiceInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CleaningServiceInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CleaningServiceInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CleaningServiceInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CleaningServiceInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToService;
    private javax.swing.JTable CleaningServiceInfoTable;
    private javax.swing.JButton Clear;
    private javax.swing.JTextField CurrentStatus;
    private javax.swing.JTextField SearchServiceName;
    private javax.swing.JTextField ServiceAvailableDay;
    private javax.swing.JTextField ServiceFee;
    private javax.swing.JTextField ServiceId;
    private javax.swing.JTextField ServiceName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
