
package ctwo;

import java.sql.Connection;
import java.util.ArrayList;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class ServiceAvailability extends javax.swing.JFrame {

    
    public ServiceAvailability() {
        initComponents();
         setLocationRelativeTo(null);
         show_user();
        
    }
    public Connection connection;  
    public ArrayList<UserT>userList()
    {
      ArrayList<UserT>userList = new ArrayList<>();

         try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=CMS", "sa", "626255");
         
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement
                    .executeQuery("select * from ServiceAvailability");
            
        
             UserT user;
            
            while(resultSet.next())
         {
            user = new UserT(resultSet.getInt("ServiceAvailabilityId"),resultSet.getInt("ServiceId"),resultSet.getString("MostAvailableStartingTime"),resultSet.getString("ServiceAvailableDay"));
            userList.add(user);

         }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
         return userList;
    
    
    
    }
      
 public void show_user()
 {
   ArrayList<UserT>list = userList();
   DefaultTableModel model =(DefaultTableModel) ServiceAvailabilityTable.getModel();
   Object[] row = new Object[4];


   for(int i = 0;i<list.size();i++)
   {  
     row[0]=list.get(i).getServiceAvailabilityId();
     row[1]=list.get(i).getServiceId();
     row[2]=list.get(i).getMostAvailableStartingTime();
     row[3]=list.get(i).getServiceAvailableDay();
     
    
     model.addRow(row);
   
   }
 
 }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ServiceAvailabilityTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BackToService = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Search = new javax.swing.JTextField();
        ServiceAvailabilityId = new javax.swing.JTextField();
        ServiceId = new javax.swing.JTextField();
        MostAvailableStartingTime = new javax.swing.JTextField();
        ServiceAvailableDay = new javax.swing.JTextField();
        Insert = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1228, 780));
        setMinimumSize(new java.awt.Dimension(1228, 780));
        setPreferredSize(new java.awt.Dimension(1228, 780));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(250, 250, 250));
        jLabel2.setText("Cleaning &");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 150, 60));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(250, 250, 250));
        jLabel3.setText("Maid Service");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 140, 70));

        ServiceAvailabilityTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ServiceAvailabilityId", "ServiceId", "MostAvailableStartingTime", "ServiceAvailableDay"
            }
        ));
        ServiceAvailabilityTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ServiceAvailabilityTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ServiceAvailabilityTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 880, 210));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Search(ServiceId)");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 130, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("ServiceAvailabilityId");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 140, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("ServiceId");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 80, 30));

        BackToService.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        BackToService.setText("BackToService");
        BackToService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToServiceActionPerformed(evt);
            }
        });
        jPanel1.add(BackToService, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 40));

        jLabel4.setBackground(new java.awt.Color(255, 204, 0));
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 160, 730));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("MostAvailableStartingTime");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("ServiceAvailableDay");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 140, 30));

        Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchKeyReleased(evt);
            }
        });
        jPanel1.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 170, 30));
        jPanel1.add(ServiceAvailabilityId, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 170, 30));
        jPanel1.add(ServiceId, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 170, 30));
        jPanel1.add(MostAvailableStartingTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 170, 30));
        jPanel1.add(ServiceAvailableDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 260, 30));

        Insert.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Insert.setText("INSERT");
        Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertActionPerformed(evt);
            }
        });
        jPanel1.add(Insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 240, 90, -1));

        Update.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Update.setText("UPDATE");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 280, -1, -1));

        Delete.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Delete.setText("DELETE");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 320, 90, -1));

        Clear.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Clear.setText("CLEAR");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        jPanel1.add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 360, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1199, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
     int opt=JOptionPane.showConfirmDialog(null,"Are You Sure To Delete","Delete",JOptionPane.YES_NO_OPTION);
       if(opt==0){
        try{
        
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
              connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=checkpointnotwo;selectMethod=cursor", "sa", "123456");
              
              int row = ServiceAvailabilityTable.getSelectedRow();
              String value = (ServiceAvailabilityTable.getModel().getValueAt(row,0).toString());
              String query ="DELETE FROM ServiceAvailability WHERE ServiceAvailabilityId="+value;
              PreparedStatement pst = connection.prepareStatement(query);
              pst.executeUpdate();
              DefaultTableModel model =(DefaultTableModel)ServiceAvailabilityTable.getModel();
              model.setRowCount(0);
              show_user();
               JOptionPane.showMessageDialog(null, "Deleted ");
              
            
        }
        
        catch(Exception e)
        {
          JOptionPane.showMessageDialog(null,e);
        }    
       }
      
    }//GEN-LAST:event_DeleteActionPerformed

    private void BackToServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToServiceActionPerformed
        Service as=new  Service();
         as.setVisible(true);
         new  ServiceAvailability().setVisible(false);
         dispose();
    }//GEN-LAST:event_BackToServiceActionPerformed

    private void ServiceAvailabilityTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ServiceAvailabilityTableMouseClicked
         int i = ServiceAvailabilityTable.getSelectedRow();
        TableModel model = ServiceAvailabilityTable.getModel();
        ServiceAvailabilityId.setText(model.getValueAt(i,0).toString());
        ServiceId.setText(model.getValueAt(i,1).toString());
        MostAvailableStartingTime.setText(model.getValueAt(i,2).toString());
        ServiceAvailableDay.setText(model.getValueAt(i,3).toString());
        
    }//GEN-LAST:event_ServiceAvailabilityTableMouseClicked

    private void SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchKeyReleased
        try {
           
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=checkpointnotwo;selectMethod=cursor", "sa", "123456");
            
            String sql ="Select*from  ServiceAvailability where  ServiceId=?";
            PreparedStatement pst = connection.prepareStatement(sql);
            pst.setString(1, Search.getText());
            ResultSet rs =pst.executeQuery();
            if(rs.next())
            {
              String setServiceAvailabilityId = rs.getString("ServiceAvailabilityId");
             ServiceAvailabilityId.setText(setServiceAvailabilityId);
              String setServiceId = rs.getString("ServiceId");
             ServiceId.setText(setServiceId);
               String setMostAvailableStartingTime = rs.getString("MostAvailableStartingTime");
              MostAvailableStartingTime.setText(setMostAvailableStartingTime);
               String setServiceAvailableDay= rs.getString("ServiceAvailableDay");
             ServiceAvailableDay.setText(setServiceAvailableDay);
               
            }
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(null, e);
         
         }
    }//GEN-LAST:event_SearchKeyReleased

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=checkpointnotwo;selectMethod=cursor", "sa", "123456");
            
            int row = ServiceAvailabilityTable.getSelectedRow();
            String Value =(ServiceAvailabilityTable.getModel().getValueAt(row,0).toString());
            String query ="UPDATE ServiceAvailability SET ServiceId=?,MostAvailableStartingTime=?,ServiceAvailableDay=? where ServiceAvailabilityId="+Value;
              PreparedStatement pst = connection.prepareStatement(query);
         
            pst.setString(1, ServiceId.getText());
            pst.setString(2, MostAvailableStartingTime.getText());
            pst.setString(3, ServiceAvailableDay.getText());
           
            pst.executeUpdate();
            DefaultTableModel model =(DefaultTableModel)ServiceAvailabilityTable.getModel();
            model.setRowCount(0);
            show_user();
            JOptionPane.showMessageDialog(null, "Updated ");
            
         
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(null,e);
         
         }
    
    }//GEN-LAST:event_UpdateActionPerformed

    private void InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertActionPerformed
        try {
          Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
              connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=checkpointnotwo;selectMethod=cursor", "sa", "123456");
         
            String query ="INSERT into ServiceAvailability (ServiceId,MostAvailableStartingTime,ServiceAvailableDay) Values(?,?,?)";
            
             PreparedStatement pst = connection.prepareStatement(query);
       
            pst.setString(1, ServiceId.getText());
            pst.setString(2,MostAvailableStartingTime.getText());
            pst.setString(3, ServiceAvailableDay.getText());
           
            
            pst.executeUpdate();
            DefaultTableModel model =(DefaultTableModel)ServiceAvailabilityTable.getModel();
            model.setRowCount(0);
            show_user();
            JOptionPane.showMessageDialog(null, "Inserted ");
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(null, e);
         
         }
    }//GEN-LAST:event_InsertActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        ServiceAvailabilityId.setText("");
         ServiceId.setText("");
         MostAvailableStartingTime.setText("");
         ServiceAvailableDay.setText("");
    }//GEN-LAST:event_ClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServiceAvailability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServiceAvailability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServiceAvailability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServiceAvailability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServiceAvailability().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToService;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Insert;
    private javax.swing.JTextField MostAvailableStartingTime;
    private javax.swing.JTextField Search;
    private javax.swing.JTextField ServiceAvailabilityId;
    private javax.swing.JTable ServiceAvailabilityTable;
    private javax.swing.JTextField ServiceAvailableDay;
    private javax.swing.JTextField ServiceId;
    private javax.swing.JButton Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
